name: Test & Coverage

on:
  workflow_call:

jobs:
  test:
    name: Ejecutar pruebas y validar cobertura
    runs-on: ubuntu-latest

    steps:
     
        # 👇 Este checkout trae el código del repo que llamó al workflow (no el del template)
        - name: Checkout del código del proyecto
          uses: actions/checkout@v4
          with:
            repository: ${{ github.repository }}
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Configurar Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Instalar dependencias
          run: npm install

        - name: Ejecutar Jest con cobertura
          run: npm test -- --coverage

        - name: Subir reporte de cobertura
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report
            path: coverage

        - name: Verificar resultados
          run: |
            echo "✅ Tests ejecutados con éxito."
            echo "📊 Reporte disponible como artefacto: coverage-report"

  quality-gate:
    name: Validar gate de calidad
    needs: test
    runs-on: ubuntu-latest
    if: \${{ success() }}
    steps:
      - run: echo "✅ Gate de calidad aprobado — se puede desplegar."
